<?php

function createCountriesEnum($context)
{
	$context->createEnum('countries', array(
		array( 'key' => 'AF', 'value' => 'Afeganistão' ),
		array( 'key' => 'ZA', 'value' => 'África do Sul' ),
		array( 'key' => 'AL', 'value' => 'Albânia' ),
		array( 'key' => 'DE', 'value' => 'Alemanha' ),
		array( 'key' => 'AD', 'value' => 'Andorra' ),
		array( 'key' => 'AO', 'value' => 'Angola' ),
		array( 'key' => 'AI', 'value' => 'Anguilla' ),
		array( 'key' => 'AQ', 'value' => 'Antártida' ),
		array( 'key' => 'AG', 'value' => 'Antígua e Barbuda' ),
		array( 'key' => 'SA', 'value' => 'Arábia Saudita' ),
		array( 'key' => 'DZ', 'value' => 'Argélia' ),
		array( 'key' => 'AR', 'value' => 'Argentina' ),
		array( 'key' => 'AM', 'value' => 'Armênia' ),
		array( 'key' => 'AW', 'value' => 'Aruba' ),
		array( 'key' => 'AU', 'value' => 'Austrália' ),
		array( 'key' => 'AT', 'value' => 'Áustria' ),
		array( 'key' => 'AZ', 'value' => 'Azerbaijão' ),
		array( 'key' => 'BS', 'value' => 'Bahamas' ),
		array( 'key' => 'BH', 'value' => 'Bahrein' ),
		array( 'key' => 'BD', 'value' => 'Bangladesh' ),
		array( 'key' => 'BB', 'value' => 'Barbados' ),
		array( 'key' => 'BY', 'value' => 'Belarus' ),
		array( 'key' => 'BE', 'value' => 'Bélgica' ),
		array( 'key' => 'BZ', 'value' => 'Belize' ),
		array( 'key' => 'BJ', 'value' => 'Benin' ),
		array( 'key' => 'BM', 'value' => 'Bermudas' ),
		array( 'key' => 'BO', 'value' => 'Bolívia' ),
		array( 'key' => 'BA', 'value' => 'Bósnia-Herzegóvina' ),
		array( 'key' => 'BW', 'value' => 'Botsuana' ),
		array( 'key' => 'BR', 'value' => 'Brasil' ),
		array( 'key' => 'BN', 'value' => 'Brunei' ),
		array( 'key' => 'BG', 'value' => 'Bulgária' ),
		array( 'key' => 'BF', 'value' => 'Burkina Fasso' ),
		array( 'key' => 'BI', 'value' => 'Burundi' ),
		array( 'key' => 'BT', 'value' => 'Butão' ),
		array( 'key' => 'CV', 'value' => 'Cabo Verde' ),
		array( 'key' => 'CM', 'value' => 'Camarões' ),
		array( 'key' => 'KH', 'value' => 'Camboja' ),
		array( 'key' => 'CA', 'value' => 'Canadá' ),
		array( 'key' => 'IC', 'value' => 'Canárias' ),
		array( 'key' => 'KZ', 'value' => 'Cazaquistão' ),
		array( 'key' => 'EA', 'value' => 'Ceuta e Melilla' ),
		array( 'key' => 'TD', 'value' => 'Chade' ),
		array( 'key' => 'CL', 'value' => 'Chile' ),
		array( 'key' => 'CN', 'value' => 'China' ),
		array( 'key' => 'CY', 'value' => 'Chipre' ),
		array( 'key' => 'SG', 'value' => 'Cingapura' ),
		array( 'key' => 'CO', 'value' => 'Colômbia' ),
		array( 'key' => 'KM', 'value' => 'Comores' ),
		array( 'key' => 'CG', 'value' => 'Congo' ),
		array( 'key' => 'KP', 'value' => 'Coréia do Norte' ),
		array( 'key' => 'KR', 'value' => 'Coréia do Sul' ),
		array( 'key' => 'CI', 'value' => 'Costa do Marfim' ),
		array( 'key' => 'CR', 'value' => 'Costa Rica' ),
		array( 'key' => 'HR', 'value' => 'Croácia' ),
		array( 'key' => 'CU', 'value' => 'Cuba' ),
		array( 'key' => 'CW', 'value' => 'Curaçao' ),
		array( 'key' => 'DG', 'value' => 'Diego Garcia' ),
		array( 'key' => 'DK', 'value' => 'Dinamarca' ),
		array( 'key' => 'DJ', 'value' => 'Djibuti' ),
		array( 'key' => 'DM', 'value' => 'Dominica' ),
		array( 'key' => 'EG', 'value' => 'Egito' ),
		array( 'key' => 'SV', 'value' => 'El Salvador' ),
		array( 'key' => 'AE', 'value' => 'Emirados Árabes Unidos' ),
		array( 'key' => 'EC', 'value' => 'Equador' ),
		array( 'key' => 'ER', 'value' => 'Eritréia' ),
		array( 'key' => 'SK', 'value' => 'Eslováquia' ),
		array( 'key' => 'SI', 'value' => 'Eslovênia' ),
		array( 'key' => 'ES', 'value' => 'Espanha' ),
		array( 'key' => 'US', 'value' => 'Estados Unidos' ),
		array( 'key' => 'EE', 'value' => 'Estônia' ),
		array( 'key' => 'ET', 'value' => 'Etiópia' ),
		array( 'key' => 'FJ', 'value' => 'Fiji' ),
		array( 'key' => 'PH', 'value' => 'Filipinas' ),
		array( 'key' => 'FI', 'value' => 'Finlândia' ),
		array( 'key' => 'FR', 'value' => 'França' ),
		array( 'key' => 'GA', 'value' => 'Gabão' ),
		array( 'key' => 'GM', 'value' => 'Gâmbia' ),
		array( 'key' => 'GH', 'value' => 'Gana' ),
		array( 'key' => 'GE', 'value' => 'Geórgia' ),
		array( 'key' => 'GI', 'value' => 'Gibraltar' ),
		array( 'key' => 'GB', 'value' => 'Grã-Bretanha (Reino Unido, UK)' ),
		array( 'key' => 'GD', 'value' => 'Granada' ),
		array( 'key' => 'GR', 'value' => 'Grécia' ),
		array( 'key' => 'GL', 'value' => 'Groelândia' ),
		array( 'key' => 'GP', 'value' => 'Guadalupe' ),
		array( 'key' => 'GU', 'value' => 'Guam (Território dos Estados Unidos)' ),
		array( 'key' => 'GT', 'value' => 'Guatemala' ),
		array( 'key' => 'GG', 'value' => 'Guernsey' ),
		array( 'key' => 'GY', 'value' => 'Guiana' ),
		array( 'key' => 'GF', 'value' => 'Guiana Francesa' ),
		array( 'key' => 'GN', 'value' => 'Guiné' ),
		array( 'key' => 'GQ', 'value' => 'Guiné Equatorial' ),
		array( 'key' => 'GW', 'value' => 'Guiné-Bissau' ),
		array( 'key' => 'HT', 'value' => 'Haiti' ),
		array( 'key' => 'NL', 'value' => 'Holanda' ),
		array( 'key' => 'HN', 'value' => 'Honduras' ),
		array( 'key' => 'HK', 'value' => 'Hong Kong' ),
		array( 'key' => 'HU', 'value' => 'Hungria' ),
		array( 'key' => 'YE', 'value' => 'Iêmen' ),
		array( 'key' => 'BV', 'value' => 'Ilha Bouvet' ),
		array( 'key' => 'AC', 'value' => 'Ilha de Ascensão' ),
		array( 'key' => 'CP', 'value' => 'Ilha de Clipperton' ),
		array( 'key' => 'IM', 'value' => 'Ilha de Man' ),
		array( 'key' => 'CX', 'value' => 'Ilha Natal' ),
		array( 'key' => 'PN', 'value' => 'Ilha Pitcairn' ),
		array( 'key' => 'RE', 'value' => 'Ilha Reunião' ),
		array( 'key' => 'AX', 'value' => 'Ilhas Aland' ),
		array( 'key' => 'KY', 'value' => 'Ilhas Cayman' ),
		array( 'key' => 'CC', 'value' => 'Ilhas Cocos' ),
		array( 'key' => 'CK', 'value' => 'Ilhas Cook' ),
		array( 'key' => 'FO', 'value' => 'Ilhas Faroes' ),
		array( 'key' => 'GS', 'value' => 'Ilhas Geórgia do Sul e Sandwich do Sul' ),
		array( 'key' => 'HM', 'value' => 'Ilhas Heard e McDonald (Território da Austrália)' ),
		array( 'key' => 'FK', 'value' => 'Ilhas Malvinas' ),
		array( 'key' => 'MP', 'value' => 'Ilhas Marianas do Norte' ),
		array( 'key' => 'MH', 'value' => 'Ilhas Marshall' ),
		array( 'key' => 'UM', 'value' => 'Ilhas Menores dos Estados Unidos' ),
		array( 'key' => 'NF', 'value' => 'Ilhas Norfolk' ),
		array( 'key' => 'SB', 'value' => 'Ilhas Salomão' ),
		array( 'key' => 'SC', 'value' => 'Ilhas Seychelles' ),
		array( 'key' => 'TK', 'value' => 'Ilhas Tokelau' ),
		array( 'key' => 'TC', 'value' => 'Ilhas Turks e Caicos' ),
		array( 'key' => 'VI', 'value' => 'Ilhas Virgens (Estados Unidos)' ),
		array( 'key' => 'VG', 'value' => 'Ilhas Virgens (Inglaterra)' ),
		array( 'key' => 'IN', 'value' => 'Índia' ),
		array( 'key' => 'ID', 'value' => 'Indonésia' ),
		array( 'key' => 'IR', 'value' => 'Irã' ),
		array( 'key' => 'IQ', 'value' => 'Iraque' ),
		array( 'key' => 'IE', 'value' => 'Irlanda' ),
		array( 'key' => 'IS', 'value' => 'Islândia' ),
		array( 'key' => 'IL', 'value' => 'Israel' ),
		array( 'key' => 'IT', 'value' => 'Itália' ),
		array( 'key' => 'JM', 'value' => 'Jamaica' ),
		array( 'key' => 'JP', 'value' => 'Japão' ),
		array( 'key' => 'JE', 'value' => 'Jersey' ),
		array( 'key' => 'JO', 'value' => 'Jordânia' ),
		array( 'key' => 'KI', 'value' => 'Kiribati' ),
		array( 'key' => 'XK', 'value' => 'Kosovo' ),
		array( 'key' => 'KW', 'value' => 'Kuait' ),
		array( 'key' => 'LA', 'value' => 'Laos' ),
		array( 'key' => 'LS', 'value' => 'Lesoto' ),
		array( 'key' => 'LV', 'value' => 'Letônia' ),
		array( 'key' => 'LB', 'value' => 'Líbano' ),
		array( 'key' => 'LR', 'value' => 'Libéria' ),
		array( 'key' => 'LY', 'value' => 'Líbia' ),
		array( 'key' => 'LI', 'value' => 'Liechtenstein' ),
		array( 'key' => 'LT', 'value' => 'Lituânia' ),
		array( 'key' => 'LU', 'value' => 'Luxemburgo' ),
		array( 'key' => 'MO', 'value' => 'Macau' ),
		array( 'key' => 'MK', 'value' => 'Macedônia (República Yugoslava)' ),
		array( 'key' => 'MG', 'value' => 'Madagascar' ),
		array( 'key' => 'MY', 'value' => 'Malásia' ),
		array( 'key' => 'MW', 'value' => 'Malaui' ),
		array( 'key' => 'MV', 'value' => 'Maldivas' ),
		array( 'key' => 'ML', 'value' => 'Mali' ),
		array( 'key' => 'MT', 'value' => 'Malta' ),
		array( 'key' => 'MA', 'value' => 'Marrocos' ),
		array( 'key' => 'MQ', 'value' => 'Martinica' ),
		array( 'key' => 'MU', 'value' => 'Maurício' ),
		array( 'key' => 'MR', 'value' => 'Mauritânia' ),
		array( 'key' => 'YT', 'value' => 'Mayotte' ),
		array( 'key' => 'MX', 'value' => 'México' ),
		array( 'key' => 'FM', 'value' => 'Micronésia' ),
		array( 'key' => 'MZ', 'value' => 'Moçambique' ),
		array( 'key' => 'MD', 'value' => 'Moldova' ),
		array( 'key' => 'MC', 'value' => 'Mônaco' ),
		array( 'key' => 'MN', 'value' => 'Mongólia' ),
		array( 'key' => 'ME', 'value' => 'Montenegro' ),
		array( 'key' => 'MS', 'value' => 'Montserrat' ),
		array( 'key' => 'MM', 'value' => 'Myanma' ),
		array( 'key' => 'NA', 'value' => 'Namíbia' ),
		array( 'key' => 'NR', 'value' => 'Nauru' ),
		array( 'key' => 'NP', 'value' => 'Nepal' ),
		array( 'key' => 'NI', 'value' => 'Nicarágua' ),
		array( 'key' => 'NE', 'value' => 'Níger' ),
		array( 'key' => 'NG', 'value' => 'Nigéria' ),
		array( 'key' => 'NU', 'value' => 'Niue' ),
		array( 'key' => 'NO', 'value' => 'Noruega' ),
		array( 'key' => 'NC', 'value' => 'Nova Caledônia' ),
		array( 'key' => 'NZ', 'value' => 'Nova Zelândia' ),
		array( 'key' => 'OM', 'value' => 'Omã' ),
		array( 'key' => 'BQ', 'value' => 'Países Baixos Caribenhos' ),
		array( 'key' => 'PW', 'value' => 'Palau' ),
		array( 'key' => 'PS', 'value' => 'Palestina' ),
		array( 'key' => 'PA', 'value' => 'Panamá' ),
		array( 'key' => 'PG', 'value' => 'Papua-Nova Guiné' ),
		array( 'key' => 'PK', 'value' => 'Paquistão' ),
		array( 'key' => 'PY', 'value' => 'Paraguai' ),
		array( 'key' => 'PE', 'value' => 'Peru' ),
		array( 'key' => 'PF', 'value' => 'Polinésia Francesa' ),
		array( 'key' => 'PL', 'value' => 'Polônia' ),
		array( 'key' => 'PR', 'value' => 'Porto Rico' ),
		array( 'key' => 'PT', 'value' => 'Portugal' ),
		array( 'key' => 'QA', 'value' => 'Qatar' ),
		array( 'key' => 'KE', 'value' => 'Quênia' ),
		array( 'key' => 'KG', 'value' => 'Quirguistão' ),
		array( 'key' => 'CF', 'value' => 'República Centro-Africana' ),
		array( 'key' => 'CD', 'value' => 'República Democrática do Congo' ),
		array( 'key' => 'DO', 'value' => 'República Dominicana' ),
		array( 'key' => 'CZ', 'value' => 'República Tcheca' ),
		array( 'key' => 'RO', 'value' => 'Romênia' ),
		array( 'key' => 'RW', 'value' => 'Ruanda' ),
		array( 'key' => 'RU', 'value' => 'Rússia (antiga URSS) - Federação Russa' ),
		array( 'key' => 'EH', 'value' => 'Saara Ocidental' ),
		array( 'key' => 'PM', 'value' => 'Saint-Pierre e Miquelon' ),
		array( 'key' => 'AS', 'value' => 'Samoa Americana' ),
		array( 'key' => 'WS', 'value' => 'Samoa Ocidental' ),
		array( 'key' => 'SM', 'value' => 'San Marino' ),
		array( 'key' => 'SH', 'value' => 'Santa Helena' ),
		array( 'key' => 'LC', 'value' => 'Santa Lúcia' ),
		array( 'key' => 'BL', 'value' => 'São Bartolomeu' ),
		array( 'key' => 'KN', 'value' => 'São Cristóvão e Névis' ),
		array( 'key' => 'MF', 'value' => 'São Martim' ),
		array( 'key' => 'SX', 'value' => 'São Martinho' ),
		array( 'key' => 'ST', 'value' => 'São Tomé e Príncipe' ),
		array( 'key' => 'VC', 'value' => 'São Vicente e Granadinas' ),
		array( 'key' => 'SN', 'value' => 'Senegal' ),
		array( 'key' => 'SL', 'value' => 'Serra Leoa' ),
		array( 'key' => 'RS', 'value' => 'Sérvia' ),
		array( 'key' => 'SY', 'value' => 'Síria' ),
		array( 'key' => 'SO', 'value' => 'Somália' ),
		array( 'key' => 'LK', 'value' => 'Sri Lanka' ),
		array( 'key' => 'SZ', 'value' => 'Suazilândia' ),
		array( 'key' => 'SD', 'value' => 'Sudão' ),
		array( 'key' => 'SS', 'value' => 'Sudão do Sul' ),
		array( 'key' => 'SE', 'value' => 'Suécia' ),
		array( 'key' => 'CH', 'value' => 'Suíça' ),
		array( 'key' => 'SR', 'value' => 'Suriname' ),
		array( 'key' => 'SJ', 'value' => 'Svalbard' ),
		array( 'key' => 'TJ', 'value' => 'Tadjiquistão' ),
		array( 'key' => 'TH', 'value' => 'Tailândia' ),
		array( 'key' => 'TW', 'value' => 'Taiwan' ),
		array( 'key' => 'TZ', 'value' => 'Tanzânia' ),
		array( 'key' => 'IO', 'value' => 'Território Britânico do Oceano índico' ),
		array( 'key' => 'TF', 'value' => 'Territórios do Sul da França' ),
		array( 'key' => 'TL', 'value' => 'Timor-Leste' ),
		array( 'key' => 'TG', 'value' => 'Togo' ),
		array( 'key' => 'TO', 'value' => 'Tonga' ),
		array( 'key' => 'TT', 'value' => 'Trinidad e Tobago' ),
		array( 'key' => 'TA', 'value' => 'Tristão da Cunha' ),
		array( 'key' => 'TN', 'value' => 'Tunísia' ),
		array( 'key' => 'TM', 'value' => 'Turcomenistão' ),
		array( 'key' => 'TR', 'value' => 'Turquia' ),
		array( 'key' => 'TV', 'value' => 'Tuvalu' ),
		array( 'key' => 'UA', 'value' => 'Ucrânia' ),
		array( 'key' => 'UG', 'value' => 'Uganda' ),
		array( 'key' => 'UY', 'value' => 'Uruguai' ),
		array( 'key' => 'UZ', 'value' => 'Uzbequistão' ),
		array( 'key' => 'VU', 'value' => 'Vanuatu' ),
		array( 'key' => 'VA', 'value' => 'Vaticano' ),
		array( 'key' => 'VE', 'value' => 'Venezuela' ),
		array( 'key' => 'VN', 'value' => 'Vietnã' ),
		array( 'key' => 'WF', 'value' => 'Wallis e Futuna' ),
		array( 'key' => 'ZM', 'value' => 'Zâmbia' ),
		array( 'key' => 'ZW', 'value' => 'Zimbábue' )
	)); 	
}
